services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - pia:/pia
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            # The following env vars are required:
            - LOC=de-frankfurt # The ids can be found here: https://serverlist.piaservers.net/vpninfo/servers/v6
            - USER=p123456
            - PASS=xxxxxxxx
            # The rest are optional:
            - LOCAL_NETWORK=10.0.0.0/16 # 192.168.1.1/24 https://www.cloudflare.com/learning/network-layer/what-is-a-subnet/
            #- KEEPALIVE=25
            - VPNDNS=1.1.1.1,1.0.0.1
        sysctls:
            # The wg-quick script tries to set this when setting up routing, however this requires running the container
            # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
            # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        # This can also be used to ensure the vpn is up before starting other containers
        # using the vpn connection
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 300s
            timeout: 10s
            retries: 3
            start_period: 30s
            start_interval: 3s
        ports:
            - 8080:8080

    qbittorrent:
        image: nephim/qbittorrentalpine
        network_mode: "service:vpn"
        # The following can be used to ensure the vpn is up and functional before the dependant service is started
        depends_on:
            vpn:
                condition: service_healthy
        volumes:
            - /your/path:/downloads # Maps to QBT_DOWNLOAD_PATH
            - /your/path:/config # Maps to QBT_CONFIG_PATH

volumes:
    pia:
